<?php

namespace Genj\SocialFeedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param int $max
     *
     * @return \Doctrine\ORM\Query
     */
    public function retrieveMostRecentPublicPosts($max = 5, $provider = null)
    {
        $query = $this->createQueryBuilder('a')
            ->where('a.isActive = :isActive')
            ->andWhere('a.publishAt <= :publishAt')
            ->orderBy('a.publishAt', 'DESC');

        if ($provider) {
            $query->andWhere('a.provider = :provider');
            $query->setParameter('provider', $provider);
        }

        $query = $query->getQuery();

        $query->setParameter('isActive', true);
        $query->setParameter('publishAt', date('Y-m-d H:i:s'));

        $query->setMaxResults($max);

        return $query;
    }
}
