<?php

namespace Genj\SocialFeedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param int    $max
     * @param string $provider
     * @param array  $authorUsernames
     *
     * @return \Doctrine\ORM\Query
     */
    public function retrieveMostRecentPublicPosts($max = 5, $provider = null, $authorUsernames = array())
    {
        $query = $this->createQueryBuilder('a')
            ->where('a.isActive = :isActive')
            ->andWhere('a.publishAt <= :publishAt')
            ->orderBy('a.publishAt', 'DESC');

        if ($provider) {
            $query->andWhere('a.provider = :provider');
            $query->setParameter('provider', $provider);
        }

        if ($authorUsernames && is_array($authorUsernames) && count($authorUsernames) > 0) {
            $query->andWhere('a.authorUsername IN(:authorUsernames)');
            $query->setParameter('authorUsernames', $authorUsernames);
        }

        $query->setParameter('isActive', true);
        $query->setParameter('publishAt', date('Y-m-d H:i:s'));

        $query->setMaxResults($max);

        return $query->getQuery()->execute();
    }
}
